trigger:
- master

resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage : Build_Push_and_Deploy_application
  jobs:
  - job: Build
    displayName: 'Build, push and deploy'
    steps:
      - task: Maven@4
        displayName: 'Maven Test and Clean Package'
        inputs:
            goals: 'clean package -DskipTests=false'

      - task: Docker@2
        displayName: 'Docker Build and Push'
        inputs:
          containerRegistry: 'jsbrcontainerregistry'
          repository: 'jsbrimagerepo'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'

      - task: AzureCLI@2
        displayName: 'Docker Image Deploy'
        inputs:
          azureSubscription: 'jsbrServiceConnection'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az webapp config container set --name $(webAppName)\
              --resource-group $(resourceGroupName)\
              --docker-registry-server-url $(registryURL)\
              --docker-registry-server-user $(registryUser)\
              --docker-registry-server-password $(registryPass)\
              --docker-custom-image-name $(imageName)
